spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telebot
    username: telebot
    password: telebot
  profiles:
    active: local

logging:
  level:
    ROOT: INFO
    org.devmpv.telebot: DEBUG

telebot:
  auth:
    username: "{$bot_username}"
    token: "{$bot_auth_token}"
open-weather:
  url: "https://api.openweathermap.org/data/2.5/"
  appid: ""

#  defaultBotOptions:
#    maxThreads: 5
#    requestConfig:
#    maxWebhookConnections: 5
#    baseUrl:
#    getUpdatesTimeout:
#    getUpdatesLimit: